# Generated by Django 3.1.4 on 2020-12-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('festival_key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'festival',
            },
        ),
        migrations.CreateModel(
            name='FestivalCategory',
            fields=[
                ('category_key', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'festival_category',
            },
        ),
        migrations.CreateModel(
            name='FestivalRegion',
            fields=[
                ('region_key', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'festival_region',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('format_key', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'format',
            },
        ),
        migrations.CreateModel(
            name='FestivalReview',
            fields=[
                ('review_key', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('festival_key', models.ForeignKey(db_column='festival_key', on_delete=django.db.models.deletion.DO_NOTHING, to='festival.festival')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='account.user')),
            ],
            options={
                'db_table': 'festival_review',
            },
        ),
        migrations.AddField(
            model_name='festival',
            name='category_key',
            field=models.ForeignKey(db_column='category_key', on_delete=django.db.models.deletion.DO_NOTHING, to='festival.festivalcategory'),
        ),
        migrations.AddField(
            model_name='festival',
            name='format_key',
            field=models.ForeignKey(db_column='format_key', on_delete=django.db.models.deletion.DO_NOTHING, to='festival.format'),
        ),
        migrations.AddField(
            model_name='festival',
            name='region_key',
            field=models.ForeignKey(db_column='region_key', on_delete=django.db.models.deletion.DO_NOTHING, to='festival.festivalregion'),
        ),
    ]
